# Generated by Django 5.2.4 on 2025-07-14 19:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_comment_likedislike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
